language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t habrich001/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true habrich001/docker-react npm run test -- --coverage